import type { Locale } from "@/i18n"
import {
  getAnalyticsKpis,
  getContentHealth,
  getDepartmentContribution,
  getTopCommunities,
} from "@/lib/db/repositories/analytics.repository"
import { listAssets } from "@/lib/db/repositories/asset.repository"
import { listBroadcastMessages, listWorkflowDefinitions, listWorkflowStages } from "@/lib/db/repositories/admin.repository"
import {
  listAuditLog,
  listComplianceMatrix,
  listFeatures,
  listGovernanceRoles,
  listMonthlyActivity,
  listSeciLayers,
  listSecurityControls,
  listTopContributors,
  listTrainingPrograms,
} from "@/lib/db/repositories/catalog.repository"
import {
  listCommunities,
  listNeeds,
  listNotifications,
  listReviewQueue,
  listTransferSessions,
} from "@/lib/db/repositories/collaboration.repository"
import {
  listCategories,
  listConfidentialityLevels,
  listKnowledgeTypeLabels,
  listLookups,
} from "@/lib/db/repositories/lookup.repository"

export async function getPlatformBootstrap(locale: Locale) {
  const [
    categories,
    knowledgeTypes,
    confidentialityLevels,
    assets,
    departments,
    fileTypes,
    searchSuggestions,
    topSearches,
    communities,
    transferSessions,
    reviewQueue,
    needs,
    notifications,
    kpis,
    departmentContribution,
    contentHealth,
    topCommunities,
    workflowStages,
    workflowDefinitions,
    broadcastMessages,
    monthlyActivity,
    topContributors,
    trainingPrograms,
    complianceMatrix,
    securityControls,
    roles,
    auditLog,
    features,
    seciLayers,
  ] = await Promise.all([
    listCategories(locale),
    listKnowledgeTypeLabels(locale),
    listConfidentialityLevels(locale),
    listAssets(locale),
    listLookups("department", locale),
    listLookups("file_type", locale),
    listLookups("search_suggestion", locale),
    listLookups("popular_search", locale),
    listCommunities(locale),
    listTransferSessions(locale),
    listReviewQueue(locale),
    listNeeds(locale),
    listNotifications(locale),
    getAnalyticsKpis(locale),
    getDepartmentContribution(locale),
    getContentHealth(locale),
    getTopCommunities(locale),
    listWorkflowStages(),
    listWorkflowDefinitions(),
    listBroadcastMessages(),
    listMonthlyActivity(locale),
    listTopContributors(locale),
    listTrainingPrograms(locale),
    listComplianceMatrix(locale),
    listSecurityControls(locale),
    listGovernanceRoles(locale),
    listAuditLog(locale),
    listFeatures(locale),
    listSeciLayers(locale),
  ])

  return {
    locale,
    categories,
    knowledgeTypes,
    confidentialityLevels,
    assets,
    departments: departments.map((item) => item.label),
    fileTypes: fileTypes.map((item) => item.label),
    searchSuggestions: searchSuggestions.map((item) => item.label),
    topSearches: topSearches.map((item) => ({
      term: item.label,
      count: Number(item.metadata?.count ?? 0),
      success: Number(item.metadata?.success ?? 0),
    })),
    communities,
    transferSessions,
    reviewQueue,
    needs,
    notifications,
    kpis,
    monthlyActivity,
    departmentContribution,
    contentHealth,
    topContributors,
    topCommunities,
    trainingPrograms,
    complianceMatrix,
    securityControls,
    roles,
    auditLog,
    features,
    seciLayers,
    workflowStages,
    workflowDefinitions,
    broadcastMessages,
  }
}
